#Register With Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 100
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
    
#Enable Hystrix
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000    
    
#Enable exposure of all the Endpoints and Check Custom Health Matrix 
#Check Endpoints at http://localhost:<port>/actuator/ 
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
        
# Logging Properties
logging:
  file:
    name: ${HOME}/logs/spring-cloud-gatway-hystrix-config/${spring.application.name}.log
    max-size: 10MB
    total-size-cap: 10MB
    max-history: 5
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    web: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    com.cts.*: DEBUG        
        
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder    
